config/routes.rb
Rails.application.routes.draw do
  resources :tags

  resources :items
  root :to => "items#index"

  
  get '*a' => redirect('/404')
  post '*a' => redirect('/404')

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  at         :date
#  spent      :float
#  note       :text
#  created_at :datetime
#  updated_at :datetime
#

class Item < ActiveRecord::Base

  has_and_belongs_to_many :tags

  validates :title,
    presence: true,
    length: { maximum: 50 }

  validates :spent,
    presence: true,
    numericality: true

  validates :note,
    length: { maximum: 1000 }

end

app/models/items_tags.rb
class ItemsTags < ActiveRecord::Base
  belongs_to :item
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  http_basic_authenticate_with(name: "satton", password: "ishikawa")

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  ITEMS_PER_PAGE = 10
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_items_per_page, only: [:index]
  before_action :get_tags, only: [:new, :edit]
  
  # GET /items
  # GET /items.json
  def index
    @items_all = Item.all.order(at: :desc)
    @items = @items_all.page(params[:page]).per(ITEMS_PER_PAGE)
    request_putter
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    begin
      @item = Item.new(item_params)
        respond_to do |format|
          if @item.save
            format.html { redirect_to items_url, notice: t("create.success") }
          else
            format.html { render :new }
            format.json { render json: @item.errors, status: :unprocessable_entity }
          end
      end
    rescue
      render :new, notice: 'Something was wrong.'
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    begin
        respond_to do |format|
          if @item.update(item_params)
            format.html { redirect_to items_url, notice: t("update.success") }
            format.json { render :show, status: :ok, location: @item }
          else
            format.html { render :edit }
            format.json { render json: @item.errors, status: :unprocessable_entity }
          end
        end
    rescue
        render :edit, notice: 'Something was wrong.'
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: t("destroy.success") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :at, :spent, :note)
    end

    def set_items_per_page
      @items_per_page = ITEMS_PER_PAGE
    end

    def request_putter
      i = 1
      puts "------------------------(；´Д`)HTTPリクエストです"
      request.env.each_pair{|key, value| puts "#{i}--#{key}:#{value}";i+=1;}
      puts "------------------------(；´Д`)以上です"
    end

    def get_tags
      @tags = Tag.order(created_at: :desc)
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :is_deleted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/items_helper.rb
module ItemsHelper
  
  #TODO! 18nできないか？ WDAYS = ["日","月","火","水","木","金","土"]
  WDAYS = ["(sun)","(mon)","(tue)","(wed)","(thr)","(fri)","(sat)"]
  
  def link_to_new
    link_to t("label.create"), new_item_path, :class => "navigate-right"
  end
  
  def link_to_tag_index
    link_to t("label.tags"), tags_url, :class => "navigate-right"
  end
  
  def getToday
    Time.zone.now.strftime("%Y-%m-%d") 
  end
  
  def getYoubi(day)
    return WDAYS[day]
  end
  
  def getTodayYoubi
    day = Time.now.wday
    return WDAYS[day]
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :at %><br>
    <%= f.date_select :at %>
  </div>
  <div class="field">
    <%= f.label :spent %><br>
    <% if @item.spent.nil? %>
      <%= f.number_field :spent, :value => 1 %>
    <% else %>
      <%= f.number_field :spent %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>

  <% if @tags %>
    <% unless @tags.size == 0 %>
      <div class="field">
        <label>tag</label><br>
        <select multiple>
          <% @tags.each do |t|%>
            <option value="<%= t.name %>"><%= t.name %></option>
          <% end %>
        </select>
      </div>
    <% end %>
<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Study-log</h1>
<p id="notice"><%= notice %></p>
<div class="card">
  <ul class="table-view">
    <li class="table-view-cell table-view-divider" style="color:black">
      <%= getToday %><%= getTodayYoubi %>
    </li>
    <li class="table-view-cell">
      <%= link_to_new %>
    </li>
    <li class="table-view-cell">
      <%= link_to_tag_index %>
    </li>
  </ul>
</div>

<% if @items_all.size > @items_per_page %>
  <div class="card">
    <ul class="table-view">
        <li class="table-view-cell">
          <%= paginate(@items) %>
        </li>
    </ul>
  </div>
<% end %>


<div class="card">
  <ul class="table-view">

  <% divider = [] %>
  <% @items.each do |item| %>
    <% unless divider.index(item.at.strftime("%Y-%m-%d"))%>
      <% divider.push(item.at.strftime("%Y-%m-%d"))%>
      <li class="table-view-cell table-view-divider" style="color:black">
        <%= item.at.strftime("%Y-%m-%d") %>
        <%= getYoubi(item.at.wday) %>
      </li>
    <% end %>

    <li class="table-view-cell">
      <a class="push-right" href="<%= edit_item_path(item) %>">
        <div>
          <%= item.title %>
        </div>
        <div>
          <b><%= item.spent %>時間</b>
        </div>
      </a>
    </li>
  <% end %>
  </ul><!-- class="table-view" -->
</div><!-- card -->

<% if @items_all.size > @items_per_page %>
  <div class="card">
    <ul class="table-view">
        <li class="table-view-cell">
      <%= paginate(@items) %>
        </li>
    </ul>
  </div>
<% end %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>At:</strong>
  <%= @item.at %>
</p>

<p>
  <strong>Spent:</strong>
  <%= @item.spent %>
</p>

<p>
  <strong>Note:</strong>
  <%= @item.note %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudyList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Dancing+Script:400,700' rel='stylesheet' type='text/css'>
  <!-- Sets initial viewport load and disables zooming  -->
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
  <!-- Makes your prototype chrome-less once bookmarked to your phone's home screen -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
</head>
<body>
<div class="content">
  <div class="content-padded">
    <%= yield %>
  </div>
 </div>
</body>
</html>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_deleted %><br>
    <%= f.check_box :is_deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Is deleted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.is_deleted %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>
<br>
<%= link_to "記録一覧へ", items_url %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Is deleted:</strong>
  <%= @tag.is_deleted %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>